# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/primary.xdc

# Block Designs: bd/top_design/top_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_design || ORIG_REF_NAME==top_design} -quiet] -quiet

# IP: bd/top_design/ip/top_design_top_0_0/top_design_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_design_top_0_0 || ORIG_REF_NAME==top_design_top_0_0} -quiet] -quiet

# IP: bd/top_design/ip/top_design_xlconstant_0_2/top_design_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_design_xlconstant_0_2 || ORIG_REF_NAME==top_design_xlconstant_0_2} -quiet] -quiet

# XDC: c:/Users/andy1/fpgaProjects/eeprom_reader/eeprom_reader.gen/sources_1/bd/top_design/top_design_ooc.xdc
