@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Jun 04 11:51:30 -0400 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim i2c_sql_rd_encoder_tb_behav -key {Behavioral:sequential_read:Functional:i2c_sql_rd_encoder_tb} -tclbatch i2c_sql_rd_encoder_tb.tcl -protoinst "protoinst_files/top_design.protoinst" -log simulate.log"
call xsim  i2c_sql_rd_encoder_tb_behav -key {Behavioral:sequential_read:Functional:i2c_sql_rd_encoder_tb} -tclbatch i2c_sql_rd_encoder_tb.tcl -protoinst "protoinst_files/top_design.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
